core/urls.py
from django.urls import path
from .views import (home, showLoginPage, showSignUpPage, login_view, signup_view,
        check_email_exist, check_username_exist, logout_view, showLogoutPage,
        user_profile, users, update_profile, products, add_product, delete_product,
        delete_product_view, UpdateProductView, category, add_category_view, UpdateCategoryView,
        delete_category, product_details, place_bid, bid_success, update_bid, adding_subscriber,
        UpdateUserProfileImage,
    )


urlpatterns = [
    # Home Page | Login | Logout | Sign Up
    path("", home, name="home"),
    path("login/", showLoginPage, name="showLoginPage"),
    path("signup/", showSignUpPage, name="showSignUpPage"),
    path("login_view/", login_view, name="login_view"),
    path("logout/", showLogoutPage, name="showLogoutPage"),
    path("logout_view/", logout_view, name="logout_view"),
    path("signup_view/", signup_view, name="signup_view"),
    path("check_email_exist/", check_email_exist, name="check_email_exist"),
    path("check_username_exist/", check_username_exist, name="check_username_exist"),

    # Users Profile
    path("user/<int:id>/profile/", user_profile, name="user_profile"),
    path("users/", users, name="users"),
    path("users/<int:id>/profile/update/", update_profile, name="update_profile"),
    path("users/<int:pk>/profile/image/update/", UpdateUserProfileImage.as_view(), name="update_profile_image"),

    # Product
    path("products/", products, name="products"),
    path("product/<int:id>/details/", product_details, name="product_details"),
    path("products/add/", add_product, name="add_product"),
    path("products/<int:id>/delete", delete_product, name="delete_product"),
    path("products/<int:id>/delete/view/", delete_product_view, name="delete_product_view"),
    path("products/<int:pk>/update/", UpdateProductView.as_view(), name="update_product_view"),

    # Category
    path("category/list/", category, name="category"),
    path("category/add/", add_category_view, name="add_category_view"),
    path("category/<int:pk>/update/", UpdateCategoryView.as_view(), name="update_category_view"),
    path("category/<int:id>/delete/", delete_category, name="delete_category"),

    # Bids
    path("bids/<int:product_id>/<int:customer_id>/place/", place_bid, name="place_bid"),
    path("bids/success/", bid_success, name="bid_success"),
    path("bids/<int:customer_id>/<int:buyproduct_id>/update/", update_bid, name="update_bid"),

    # Subscribers
    path("subscribe/", adding_subscriber, name="adding_subscriber"),

]

mnadaonline/urls.py
from django.contrib import admin
from django.urls import path, include
from mnadaonline import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone
import datetime
from dateutil.relativedelta import relativedelta



class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = [
            "-id"
        ]
    


class Product(models.Model):
    """ Product """
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField(max_length=2500)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/")
    status = models.CharField(
        max_length=1,
        choices = (
            ("a", "Available"),
            ("u", "Unavailable"),
        ),
        default = "a"
    )
    sold = models.BooleanField(default=False)
    new = models.BooleanField(default=False)
    valid_until = models.DateTimeField()

    def get_time_left(self):
        t_diff = relativedelta(self.valid_until.replace(tzinfo=None), timezone.now().replace(tzinfo=None))
        return "{h}H {m}M".format(
            h=t_diff.hours,
            m=t_diff.minutes,
            # s=t_diff.seconds
        )

    def display_status(self):
        for _ in Product.objects.all():
            if _ == self:
                if _.valid_until > timezone.now():
                    _.status = "a"
                    _.save()
                else:
                    _.status = "u"
                    _.save()

        return self.status
    
    def bid_winner(self):
        now = timezone.now()
        customer_placed_bids = []
        if self.valid_until < now:
            for x in BuyProduct.objects.all():
                if x.product.id == self.id:
                    customer_placed_bids.append(x.customer_price)
        
        maximum_placed_bid = max(customer_placed_bids)
        winner = BuyProduct.objects.filter(
            customer_price = maximum_placed_bid,
            product = self
        ).first()
        winnerObj = winner.customer
        winnerObj.stars = winnerObj.stars + 1
        winnerObj.save()
        
        return winnerObj
    
    if __name__ == "__product__":
        display_status()
    
    def get_total_bids(self) -> int():
        """ This returns the total number of customers placed bids """
        bids_counter = int()
        for p in Product.objects.all():
            for b in p.buyproduct_set.all():
                if b.product == self:
                    bids_counter += 1
        return bids_counter

    def __str__(self):
        return "{}-{}".format(self.name, self.status)
    
    class Meta:
        ordering = [
            "-id"
        ]


class BuyProduct(models.Model):
    customer = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer_price = models.IntegerField()

    def top_priced_customer(self):
        return BuyProduct.objects.all().order_by("-customer_price")
    
    def __str__(self):
        return "{}-{}".format(self.customer, self.product)
    
    def percentage_calc(self) -> int():
        return round((self.customer_price/self.product.price) * 100, 2)
    
    def price_bar_color(self):
        title = str()
        if self.customer_price > self.product.price:
            return "success"
        elif self.customer_price < self.product.price:
            title = "BID PRICE PLACED IS {} LESS THAN PRODUCT PRICE.".format(
                self.percentage_calc()
            )
            return "danger"
        else:
            return "secondary"
        
    def get_title(self):
        title = str()
        if self.customer_price > self.product.price:
            title = "BID PRICE PLACED IS {}% OF THE PRODUCT PRICE.".format(
                self.percentage_calc()
            )
        elif self.customer_price < self.product.price:
            title = "BID PRICE PLACED IS {}% OF THE PRODUCT PRICE.".format(
                self.percentage_calc()
            )
        else:
            title = "BID PRICE PLACED IS 100% OF THE PRODUCT PRICE."
        return title
    

    class Meta:
        ordering = [
            "-customer_price"
        ]


class UserProfile(AbstractUser):
    """ Profile Of The User """
    photo = models.ImageField(
        verbose_name="Profile Picture",
        upload_to="users/images/",
        null=True,
        blank=True
    )
    phone = models.CharField(
        max_length=13,
        null=True,
        blank=True
    )
    address = models.TextField(
        max_length=100,
        null=True,
        blank=True
    )
    stars = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return self.username
    
    
class Subscriber(models.Model):
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.email

    class Meta:
        ordering = [
            "-id"
        ]  
        verbose_name_plural = "Subscribers"
      

core/forms.py
from django import forms



class AddProductImageForm(forms.Form):
    product_photo = forms.FileField(required=True,widget=forms.FileInput(attrs={
        "class": "form-control", "id": "photo", "name": "product_photo","accept": "image/*", "type": "file"
    }))


# class Update

core/templates/core/bid_success.html
{% extends 'core/common/base.html' %}
{% load humanize %}
{% block content %}
<div class="bg-light py-3">
  <div class="container">
    <div class="row">
        <div class="col-md-12 mb-0">
          <a href="{% url 'home' %}">Home</a> 
          <span class="mx-2 mb-0">/</span>
          <strong class="text-black">Bid Placed</strong>
        </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
      <div class="site-section">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center">
              <span class="icon-check_circle display-3 text-success"></span>
              <h2 class="display-3 text-black">Thank you!</h2>
              <p class="lead mb-5">Your bid was successfuly placed. You can always upgrade your bid price if time allows.</p>
              <p><a href="{% url 'home' %}" class="btn btn-sm btn-primary">Back to shop</a></p>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock content %}

core/templates/core/category_list.html
{% extends 'core/common/base.html' %}
{% load humanize %}
{% block custom_css %}
<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
    }
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }
    .close:hover,
    .close:focus {
        color: #000;
        text-decoration: none;
        cursor: pointer;
    }
</style>  
{% endblock custom_css %}
{% block content %}
<div class="bg-light py-3">
  <div class="container">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Category List</li>
      </ol>
    </nav>
    <!-- /Breadcrumb -->
    <div class="row">

    </div>
  </div>
</div>
{% include "core/common/messages.html" %}
<div class="site-section">
    
    <div class="site-section" style="margin-top: -100px;">
    <div class="container">
        <div class="row mb-5">
        <a href="{% url 'add_category_view' %}">
            <button id="openModal" class="btn btn-secondary mb-3 ml-3"><span class="icon icon-plus"></span>Add Category</button>
        </a>
        <form class="col-md-12" method="post">
            <div class="site-blocks-table">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="product-thumbnail">S/N</th>
                    <th class="product-name">Name</th>
                    <th class="product-remove">Number of Products</th>
                    <th class="product-remove">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for category in category_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td class="product-name">
                    <h2 class="h5 text-black">{{ category.name.title }}</h2>
                    </td>
                    <td>{{ category.product_set.count }}</td>
                    <td>
                        <a href="{% url 'update_category_view' category.id %}"><span title="Update {{ category.name }}" style="color: blue" class="icon icon-edit ml-2"></span></a>
                        <a href="{% url 'delete_category' category.id %}"><span title="Delete {{ category.name }}" style="color: red" class="icon icon-trash ml-2"></span></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </form>
        </div>
    </div>
    </div>
</div>

<!-- Add Product Modal -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>Some text in the Modal..</p>
    </div>
</div>
{% endblock content %}
{% block custom_js %}
  <script type="text/javascript">
      var modal = document.getElementById("myModal");
      var btn = document.getElementById("openModal");
      var span = document.getElementsByClassName("close")[0];

      btn.onclick = function() {
          modal.style.display = "none";
      }

      window.onclick = function(event) {
          if(event.target == modal){
              modal.style.display = "none";
          }
      }
  </script>
{% endblock custom_js %}

core/templates/core/delete_category.html
{% extends 'core/common/base.html' %}
{% block content %}
<div class="bg-light py-3">
  <div class="container">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'category' %}">Category</a></li>
        <li class="breadcrumb-item active" aria-current="page">Delete {{ object.name }}</li>
      </ol>
    </nav>
    <!-- /Breadcrumb -->
    <div class="row">

    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row">
      {% include "core/common/messages.html" %}
      <div class="col-md-12">
        <form method="POST">
          {% csrf_token %}
          <div class="p-3 p-lg-5 border">
            <input type="hidden" name="username" class="form-control" value="{{ request.user.username }}">
            <div class="mb-3">
              <p style="text-align: center;color: red;">Once you delete this category you will not be able to recover it.</p>
              <p style="text-align: center;color: red;"> This category holds {{ object.product_set.count }} Products. {{ object.product_set.count }} products will also be deleted.</p>
              <h4 style="text-align: center;">Are you sure to delete?</h4>
            </div>

            <div class="form-group row">
              <div class="col-lg-12">
                <input type="submit" class="btn btn-outline-danger btn-lg btn-block mb-3" value="delete">
              </div>

            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/delete_product.html
{% extends 'core/common/base.html' %}
{% block content %}
<div class="bg-light py-3">
  <div class="container">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'products' %}">Products</a></li>
        <li class="breadcrumb-item active" aria-current="page">Delete {{ object.name }}</li>
      </ol>
    </nav>
    <!-- /Breadcrumb -->
    <div class="row">

    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row">
      {% include "core/common/messages.html" %}
      <div class="col-md-12">
        <form method="POST" action="{% url 'delete_product_view' object.id %}">
          {% csrf_token %}
          <div class="p-3 p-lg-5 border">
            <input type="hidden" name="username" class="form-control" value="{{ request.user.username }}">
            <div class="mb-3">
              <p style="text-align: center;color: red;">Once you delete this product you will not be able to recover it.</p>
              <h4 style="text-align: center;">Are you sure to delete?</h4>
            </div>

            <div class="form-group row">
              <div class="col-lg-12">
                <input type="submit" class="btn btn-outline-danger btn-lg btn-block mb-3" value="delete">
              </div>

            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/index.html
{% extends "core/common/base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
{% include "core/common/messages.html" %}
<div class="site-blocks-cover" style="background-image: url({{ latest.image.url }});width: 100%" data-aos="fade">
  <div class="container">
    <div class="row align-items-start align-items-md-center justify-content-end">
      <div class="col-md-5 text-center text-md-left pt-5 pt-md-0">
        <h1 class="mb-2">Perfect Products, <br> Low Price</h1>
        <div class="intro-text text-center text-md-left">
          <p class="mb-4">It is only here where you can get these quality products with low price. Take your chance by placing a Bid!</p>
          <p>
            <a href="#featured-products" class="btn btn-sm btn-primary shop-now-btn">Shop Now</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="site-section site-section-sm site-blocks-1">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
        <div class="icon mr-4 align-self-start">
          <span class="icon-truck"></span>
        </div>
        <div class="text">
          <h2 class="text-uppercase">Free Shipping</h2>
          <p>We offer free shipping to our beloved customers around Tanzania with condition of half-payment(advance fee) which is about 50% of the product price.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
        <div class="icon mr-4 align-self-start">
          <span class="icon-refresh2"></span>
        </div>
        <div class="text">
          <h2 class="text-uppercase">Free Returns</h2>
          <p>In MnadaOnline customer comes first, we value our customers the most and that includes customers satisfaction. So to guarantee you that we accept product returns if customer is not satisfied. Just to make you happy 😊!</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
        <div class="icon mr-4 align-self-start">
          <span class="icon-help"></span>
        </div>
        <div class="text">
          <h2 class="text-uppercase">Customer Support</h2>
          <p>To make sure our service is available 24/7, we have a solid and very active customer care that offers instant feedbacks.</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="site-section block-3 site-blocks-2 bg-light">
  <div class="container">
    <div class="row justify-content-center" id="featured-products">
      <div class="col-md-7 site-section-heading text-center pt-4">
        <h2>Featured Products</h2>
      </div>
    </div>
    <div class="row actual-shop">
      <div class="col-md-12">
        <div class="nonloop-block-3 owl-carousel">
          {% for product in products %}
          <div class="item">
            <div class="block-4 text-center">
              <figure class="block-4-image">
                <a href="{% url 'product_details' product.id %}">
                  <img src="{{ product.image.url }}" alt="Image placeholder" class="img-fluid">
                </a>
              </figure>
              <div class="block-4-text p-4">
                <h3><a href="#">{{ product.name.title }}</a></h3>
                <p class="mb-0">Valid Until: {{ product.valid_until }}</p>
                {% if product.get_time_left|slice:"1" == '-' %}
                <p class="mb-0">Time Passed: <span style="color: red;">Bidding Closed</span></p>
                {% else %}
                <p class="mb-0">Time Left: {{ product.get_time_left }}</p>
                {% endif %}
                <p class="mb-0">Bids Placed: {{ product.get_total_bids }}</p>
                <p class="text-primary font-weight-bold">TZS {{ product.price|intcomma }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="site-section block-8">
  <div class="container">
    <div class="row justify-content-center  mb-5">
      <div class="col-md-7 site-section-heading text-center pt-4">
        <h2>Big Sale!</h2>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col-md-12 col-lg-7 mb-5">
        <a href="{%url 'product_details' big_sale.product.id %}"><img src="{{ big_sale.product.image.url }}" alt="{{ big_sale.product.name.title }}" class="img-fluid rounded"></a>
      </div>
      <div class="col-md-12 col-lg-5 text-center pl-md-5">
        <h2><a href="{%url 'product_details' big_sale.product.id %}">{{ big_sale.percentage_calc }}% than product price</a></h2>
        <p class="post-meta mb-4">Won By <a href="#">{{ big_sale.product.bid_winner.get_full_name }}</a> <span class="block-8-sep">&bullet;</span>
        <p>{{ big_sale.product.description|safe }}</p>
        <p><a href="#featured-products" class="btn btn-primary btn-sm">Shop Now</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/core/update_category.html
{% extends 'core/common/base.html' %}
{% load humanize %}
{% block custom_css %}
  <style>
      #id_name,#id_price,#id_category,#id_image,#id_description {
        display: block;
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out, -webkit-box-shadow 0.15s ease-in-out;
    }
      #id_name:active, #id_name:focus {
        border-color: #7971ea;
    }
  </style>
{% endblock custom_css %}
{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <!-- Breadcrumb -->
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'category' %}">Category List</a></li>
                <li class="breadcrumb-item active" aria-current="page">Update {{ object.name }}</li>
            </ol>
        </nav>
        <!-- /Breadcrumb -->
        <div class="row">

        </div>
    </div>
</div>

<div class="site-section">
    {% include "core/common/messages.html" %}
    <div class="site-section" style="margin-top: -100px;">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <h2 class="h3 mb-3 text-black">Update {{ object.name }}</h2>
                </div>
                <div class="col-md-12">

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="p-3 p-lg-5 border">
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <label for="product_name" class="text-black">Product Name <span
                                            class="text-danger">*</span></label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-12">
                                    <input type="submit" class="btn btn-primary btn-lg btn-block mb-3" value="Update">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/update_product.html
{% extends 'core/common/base.html' %}
{% load humanize %}
{% block custom_css %}
  <style>
      #id_name,#id_price,#id_category,#id_image,#id_description,#id_valid_until {
        display: block;
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out, -webkit-box-shadow 0.15s ease-in-out;
    }
      #id_name:active, #id_name:focus {
        border-color: #7971ea;
    }
  </style>
{% endblock custom_css %}
{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <!-- Breadcrumb -->
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'products' %}">Products</a></li>
                <li class="breadcrumb-item active" aria-current="page">Update {{ object.name }}</li>
            </ol>
        </nav>
        <!-- /Breadcrumb -->
        <div class="row">

        </div>
    </div>
</div>

<div class="site-section">
    {% include "core/common/messages.html" %}
    <div class="site-section" style="margin-top: -100px;">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <h2 class="h3 mb-3 text-black">Update {{ object.name }}</h2>
                </div>
                <div class="col-md-12">

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="p-3 p-lg-5 border">
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="product_name" class="text-black">Product Name <span
                                            class="text-danger">*</span></label>
                                    {{ form.name }}
                                </div>
                                <div class="col-md-6">
                                    <label for="product_price" class="text-black">Product Price <span
                                            class="text-danger">*</span></label>
                                    {{ form.price }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <label for="category" class="text-black">Product Category <span
                                            class="text-danger">*</span>
                                    </label>
                                    {{ form.category }}
                                </div>
                                <div class="col-md-6">
                                    <label for="photo" class="text-black">Product Image <span
                                            class="text-danger">*</span></label>
                                    {{ form.image }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <label for="description" class="text-black">Product Description <span
                                            class="text-danger">*</span></label>
                                    {{ form.description }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <label for="new_product" class="text-black">Product Condition <span
                                            class="text-danger"></span>
                                    </label>
                                    <div class="mb-1 d-flex">
                                        <label for="option-sm" class="d-flex mr-3 mb-3">
                                          <span class="d-inline-block mr-2" style="top:-2px; position: relative;">{{ form.new }}</span> <span class="d-inline-block text-black">{{ form.new.label }}</span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12 mb-3">
                                    <label for="id_valid_until" class="text-black">Valid Until <span
                                        class="text-danger">*</span>
                                    </label>
                                    {{ form.valid_until }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-12">
                                    <input type="submit" class="btn btn-primary btn-lg btn-block mb-3" value="Update">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}